FROM texlive/texlive:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y make latexmk graphviz dot2tex gnuplot git && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb && \
    dpkg -i pandoc-2.5-1-amd64.deb && \
    rm pandoc-2.5-1-amd64.deb

WORKDIR /work

# run this via `make docker` to use pandoc on local system (hopefully v2.5)
CMD ["make"]
