name: Build WP

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: 'self-hosted'

    steps:
      - uses: actions/checkout@v2

      - name: build docker container
        shell: bash
        run: |
          make docker-build

      - name: build whitepaper
        run: |
          # make standalone graphics explicitly & in parallel
          NCPUS=$(lscpu | egrep '^CPU\(s\)' | awk '{ print $2 }')
          make -j ${NCPUS:-4} docker "DOCKER_CMD=make wp-graphics-standalone"
          # make the rest of the whitepaper
          make docker "DOCKER_CMD=bash build.sh"
