name: Build WP

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: 'self-hosted'

    steps:
      - uses: actions/checkout@v2

      - name: build docker container
        shell: bash
        run: |
          make docker-build

      - uses: purescript-contrib/setup-purescript@main
      - run: |
          cd includes/ut/complexity/ut-complexity-gen-purs
          #LAMW_URL="https://raw.githubusercontent.com/XertroV/lambertw/7c65e241b353e296f58cdad774c77d500d0a11bd/lambertw.js"
          #curl "$LAMW_URL" > src/LambertW.js
          #echo "exports.gsl_sf_lambert_W0 = gsl_sf_lambert_W0;" >> src/LambertW.js
          spago test
          spago build
          npm run bundle-for-wp

      - name: lint whitepaper
        run: |
          make docker "DOCKER_CMD=bash -c 'make cilint'"
          make docker "DOCKER_CMD=bash -c 'make release'" || true
          # No matches for \todo{ should be found
          grep -qzv '\\todo{' output/whitepaper.tex

      - name: build whitepaper
        run: make docker "DOCKER_CMD=bash build.sh"
