name: Build WP Draft

on:
  pull_request:
    branches:
      - master
      - main
      - 'pre-*'
      - 'prerelease-*'
      - 'pre-release-*'
      - 'releases/**'

jobs:
  call-wp-workflow:
    uses: ./.github/workflows/build-wp.yml
    with:
      build_release: true
