name: Test PoR Sim (Rust)

on:
  push:
    branches: '*'

jobs:
  test:
    runs-on: 'self-hosted'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: run cargo test
        run: |
          cd experiments/por-sim-rs
          cargo test
